# Generated by Django 4.2.4 on 2023-08-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "categories",
                "db_table": "categories",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="images/sliders/")),
            ],
            options={
                "verbose_name": "Slider",
                "verbose_name_plural": "Sliders",
                "db_table": "sliders",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "tags",
                "db_table": "tags",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="frontend.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "sub_categories",
                "db_table": "sub_categories",
                "managed": True,
            },
        ),
    ]
