# Generated by Django 4.2.4 on 2023-08-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
                ("view", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "posts",
                "db_table": "posts",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "tags",
                "db_table": "tags",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="slider",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
