# Generated by Django 4.2.4 on 2023-08-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("view", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
                ("image", models.ImageField(null=True, upload_to="images/posts/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("trending", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="frontend.category",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="frontend.subcategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="posts", to="frontend.tag"),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "posts",
                "db_table": "posts",
                "managed": True,
            },
        ),
    ]
