# Generated by Django 4.2.4 on 2023-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(null=True, upload_to="images/category/"),
        ),
    ]
