# Generated by Django 4.2.4 on 2023-08-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_alter_slider_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="slider",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
