# Generated by Django 4.2.4 on 2023-08-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_alter_category_image_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/sliders/"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
