# Generated by Django 4.2.4 on 2023-08-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_alter_category_title_alter_slider_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
