# Generated by Django 4.2.4 on 2023-08-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0008_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="posts", to="frontend.tag"),
        ),
    ]
