# Generated by Django 4.2.4 on 2023-08-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0010_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="frontend.subcategory",
            ),
        ),
    ]
